# Generated by Django 4.2 on 2023-04-11 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('logo_img', models.ImageField(blank=True, upload_to='events_images', verbose_name='Логотип')),
                ('suvenir_img', models.ImageField(blank=True, upload_to='events_images', verbose_name='Сувенир')),
                ('date_sorev', models.DateField(blank=True, verbose_name='Дата проведения')),
                ('is_no_view', models.BooleanField(default=False, verbose_name='Не показывать')),
                ('url_in_internet', models.CharField(blank=True, max_length=100, verbose_name='Подробная информация')),
                ('id_in_iorient', models.IntegerField(blank=True, default=0, verbose_name='Id на iorient.ru')),
            ],
            options={
                'verbose_name': 'Соревнование',
                'verbose_name_plural': 'Соревнования',
                'ordering': ['-date_sorev'],
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fam', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('nam', models.CharField(blank=True, max_length=40, verbose_name='Имя')),
                ('ptr', models.CharField(blank=True, max_length=40, verbose_name='Отчество')),
                ('brd', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('pol', models.CharField(blank=True, max_length=1, verbose_name='Пол')),
                ('gorod', models.CharField(blank=True, max_length=100, verbose_name='Населенный пункт')),
                ('telefon', models.CharField(blank=True, max_length=30, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Адрес электронной почты')),
                ('photo', models.ImageField(blank=True, upload_to='peoples_images', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'ordering': ['fam', 'nam', 'ptr'],
            },
        ),
        migrations.CreateModel(
            name='PeopleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reiting', models.FloatField(blank=True, default=0, verbose_name='Рейтинг')),
                ('zoloto', models.BooleanField(default=False)),
                ('serebro', models.BooleanField(default=False)),
                ('bronza', models.BooleanField(default=False)),
                ('event', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.event')),
                ('people', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.people')),
            ],
            options={
                'verbose_name': 'Участник соревнования',
                'verbose_name_plural': 'Участники соревнований',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='abs_people',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.people'),
        ),
    ]
