# Generated by Django 4.2 on 2023-04-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_num_com_event_num_people_event_num_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Информация'),
        ),
    ]
